name: Build for Safari

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [22.x, 23.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install xcrun
        run: sudo xcode-select -s /Library/Developer/CommandLineTools
      - name: Install Safari Web Extension Converter
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Install Packages
        run: npm install
      - name: Build
        run: npm run release-safari
      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-safari-${{ matrix.node-version }}
          path: dist-safari
